package:
    name: gtsam
    version: 3.2.1

source:
    fn: gtsam-3.2.1.tar.gz
    url: https://bitbucket.org/gtborg/gtsam/get/3.2.1.tar.gz
    md5: 699068a0777102a45ced326ca11c3b22
  
build:
    number: 0

requirements:
    build:
        - cmake
        - eigen
        - numpy
        - boost ==1.57.0

    run:
        - cmake
        - boost ==1.57.0

about:
    home: https://bitbucket.org/gtborg/gtsam
    license: BSD
    summary: Georgia Tech Smoothing and Mapping library
