package:
    name: pyisam

source:
  path: pyisam
  
build:
    number: 0

requirements:
    build:
        - numpy
        - python
        - isam

    run:
        - python
        - numpy
        - isam

about:
    home: 
    license: BSD
