package:
    name: pygtsam
    version: 3.2.1

source:
    git_url: https://github.com/spillai/pygtsam.git
    git_branch: master

build:
    number: 0

requirements:
    build:
      - python
      - cmake
      - numpy
      - gtsam
      - boost ==1.57.0
      - eigen

    run:
      - python
      - numpy
      - gtsam
      - boost ==1.57.0
      - eigen

about:
    home: https://collab.cc.gatech.edu/borg/gtsam/
    license: BSD
    summary: Georgia Tech Smoothing and Mapping library (Python)
