package:
    name: pygtsam

source:
  path: pygtsam
  
build:
    number: 0

requirements:
    build:
      - python
      - cmake
      - numpy
      - mkl
      - gtsam
      - zlib
      - pkg-config
        
    run:
      - python
      - numpy
      - mkl
      - zlib
      - gtsam
      - pkg-config
about:
    home: 
    license: BSD
